apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bizBrainz.fullname" . }}
  namespace: {{ include "bizBrainz.namespace" . }}
  labels:
    {{- include "bizBrainz.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.applicationConfig }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}		
  {{- end }}
  {{- end }}
