---
- name: deploy cloud init config file
  template: src=templates/cloud-config.cfg dest=/etc/cloud/cloud.cfg.d/defaults.cfg
  become: yes

- name: create group bizBrainz
  group: name={{ cloud_user }} state=present
  become: yes

- name: create user bizBrainz
  user: name={{ cloud_user }} groups={{ cloud_group }}
  become: yes


- name: create user {{ default_user }}
  user: name={{ default_user }} groups={{ cloud_group }}
  become: yes


- name: add sudoers group for user {{ cloud_user }}
  copy:
    content: 'bizBrainz ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/bizBrainz
    mode: 0440
    owner: root
    group: root
  become: yes
