#!/bin/bash

set -o errexit
set -o nounset

mkdir -p /root/bizBrainz

cd /root/bizBrainz

# Step 1: Download the templates
echo "Downloading the Docker Compose file..."
curl -L https://bit.ly/3AQzII6 -o $PWD/docker-compose.yml

# Step 2: Pulling the latest container images
echo ""
echo "Pulling the latest container images"
docker-compose pull

# Step 3: Starting the Bizbrainz containers
echo "Starting the Bizbrainz containers"
docker-compose up --detach --remove-orphans
